[package]
name = "window-auto-hide"
version = "0.1.0"
authors = ["fc1943s <fc1943s@gmail.com>"]
edition = "2018"

[dependencies]
pathsearch = "0.2.0"
toml = "0.5.6"
serde = { version = "1.0.112", features = ["derive"] }

eventual = "0.1.7"

windows-win = "2.4.0"
